name: CI

on:
  push:
    branches:
      - main

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent direct push to main
        run: |
          echo "❌ Direct pushes to main branch are not allowed!"
          echo "Please create a pull request instead."
          exit 1